version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/frontend-vite"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/next-app"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    versioning-strategy: increase
    directory: "/backend-python"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      poetry-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
