logging:
  level:
    org.springframework.security: info

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          next-app-client:
            registration:
              redirect-uris:
                - "https://vicx.no/api/auth/callback/next-app-client"
              post-logout-redirect-uris:
                - "https://vicx.no/"
              scopes:
                - "openid"
