server:
  port: 9000
  servlet:
    context-path: /auth-server

logging:
  level:
    org.springframework.security: DEBUG

app-user:
  name: ${DEFAULT_USERNAME:user1}
  password: "${DEFAULT_PASSWORD:password}"

oauth:
  client-id: "next-app-client"
  client-secret: ${CLIENT_SECRET:secret}
  redirect-uri: ${REDIRECT_URI:http://localhost:3000/api/auth/callback/next-app-client}
  post-logout-redirect-uri: ${POST_LOGOUT_REDIRECT_URI:http://localhost:3000/}

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:h2:mem:testdb;CACHE_SIZE=2048
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate.ddl-auto: create
    show-sql: false

  h2:
    console:
      enabled: false
      path: /h2-console

management:
  server:
    port: 8081
  health:
    livenessstate:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true