spring:
  application:
    name: vicx-backend-spring-boot

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always