logging:
  level:
    root: INFO

spring:
  application:
    name: vicx-backend-spring-boot

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9000/auth-server}

management:
  server:
    port: 8082
  health:
    livenessstate:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true