logging:
  level:
    root: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

