spring:
  application:
    name: vicx-backend-spring-boot

management:
  server:
    port: 8081
  health:
    livenessstate:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true