logging:
  level:
    root: INFO

recaptcha:
  secret: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe # dev secret

spring:
  servlet:
    multipart:
      enabled: true

  application:
    name: vicx-backend-spring-boot

  # for adding GitHub as well:
  # https://docs.spring.io/spring-security/reference/reactive/oauth2/resource-server/multitenancy.html
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9000/auth-server}

  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;CACHE_SIZE=2048
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate.ddl-auto: create
    show-sql: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  flyway:
    enabled: false

management:
  server:
    port: 8082
  health:
    livenessstate:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true