spring:
  application:
    name: spring-react-calculator

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always

server:
  tomcat:
    accept-count: 0 # 0 to prevent queuing of requests
    max-connections: 1
    threads:
      max: 1