spring:
  application:
    name: spring-react-calculator

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always