name: Build backend-spring-boot Docker and push

on:
  push:
    branches:
      - main
    tags:
      - '*'
#    paths:
#      - 'backend-spring-boot/**'

  pull_request:
    paths:
      - 'backend-spring-boot/**'

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yml
    secrets: inherit
    with:
      appName: "backend-spring-boot"
      dockerContext: "./backend-spring-boot"
