name: Build Docker and Push

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  APP_NAME: snake-game

jobs:
  build_and_push_docker_snake_game:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract repository owner
        id: extract_repo
        run: |
          echo "REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)" >> $GITHUB_ENV

      - name: Set Docker image environment variable
        run: |
          # Construct the Docker image name using extracted owner
          echo "DOCKER_IMAGE=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.APP_NAME }}:${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }} ./snake-game

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE }}
