name: next-app run tests

on:
  push:
    branches:
      - main
    paths:
      - 'next-app/**'

  pull_request:
    paths:
      - 'next-app/**'

jobs:
  next_app_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests with Gradle
        run: ./gradlew -p next-app runJest --build-cache --info